# Files for typos
# Instruction:  https://github.com/marketplace/actions/typos-action#getting-started

[default.extend-identifiers]
noInferrableTypes = "noInferrableTypes"

[default.extend-words]

[files]
extend-exclude = ['package*.json', '*.min.js']
